# Generated by Django 3.2.12 on 2022-05-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_controller', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('once_off_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('add_promotional_price', models.BooleanField(default=False)),
                ('promotion_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('contract_monthly_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('price_term', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Select Price Term'), (1, 'Twelve Months'), (2, 'Twenty Four Months'), (3, 'Thirty Six Months'), (4, 'Month To Month'), (5, 'Once Off')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, default=None)),
                ('unpublish_date', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_controller.publishproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_controller.productprice'),
        ),
    ]
