version: "3"

services:
  web:
    build: .
    command: bash -d "python3 manage.py runserver 0.0.0.0:8000"
    container_name: api
    restart: always
    volumes:
      - .:/api`
    ports:
      - "8000:8000"
    networks:
      - ecommerce_net



  networks:
    ecommerce_net:
      driver: bridge